name: Build Dotfiles

on:
  push:
    branches:
      - add-build
  pull_request:
  schedule:
    - cron: '0 22 * * *'

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Run build
        run: bash ./build.sh
